### ISSUE TITLE
Bug: Exchange rates missing

### ISSUE THREAD

**Issue by zachgoll** [maybe-finance/maybe#1399]
**Describe the bug**

The sync process is now throwing errors for exchange rate conversions:

![image](https://github.com/user-attachments/assets/85ef542e-e113-40a8-9068-67cb5e506293)

**To Reproduce**
1. Set family currency to `USD`
2. Create an account in `EUR`
3. Sync the `EUR` account

**Expected behavior**

If Synth is configured in the environment, exchange rates should sync correctly.

**Comment by zachgoll** [comment]
Fixed in latest version.

**Comment by TheoSigaud** [comment]
![Capture d'écran 2024-11-08 112826](https://github.com/user-attachments/assets/08e33d16-f5f4-4da4-af9e-b37c5f919dad)

After updating the application, the problem is still present

**Comment by zachgoll** [comment]
@TheoSigaud I see you've updated the application, but have you hit the "Sync" button on this account again?  If that doesn't work for you, we can re-open.

**Comment by bennypowers** [comment]
Having hit "sync" just now...

```json
{
  "dates": [
    "2024-10-14",
    "2024-10-15",
    "2024-10-16",
    "2024-10-17",
    "2024-10-18",
    "2024-10-19",
    "2024-10-20",
    "2024-10-21",
    "2024-10-22",
    "2024-10-23",
    "2024-10-24",
    "2024-10-25",
    "2024-10-26",
    "2024-10-28",
    "2024-10-29",
    "2024-11-01",
    "2024-11-02",
    "2024-11-03",
    "2024-11-04",
    "2024-11-05",
    "2024-11-06",
    "2024-11-07",
    "2024-11-08"
  ],
  "to_currency": "ILS",
  "from_currency": "USD"
}
```

**Comment by TheoSigaud** [comment]
> @TheoSigaudJe vois que vous avez mis à jour l'application, mais avez-vous à nouveau appuyé sur le bouton « Synchroniser » sur ce compte ? Si cela ne fonctionne pas pour vous, nous pouvons rouvrir.

Yes always the same problem 

![image](https://github.com/user-attachments/assets/1546519b-6590-445d-bf64-dcc94014e620)

**Comment by TheoSigaud** [comment]
![image](https://github.com/user-attachments/assets/0e199c9e-b51a-4763-865c-b6e2733e41f0)

**Comment by TheoSigaud** [comment]
I deleted the bugged accounts and recreated the accounts with the same transactions.

**Comment by zachgoll** [comment]
@TheoSigaud thanks for the update!

**Comment by zachgoll** [comment]
I'm going to close this out as I'm not able to reproduce locally with the latest version of the app.

My guess is that this error is a result of _stale_ data lingering on some self-hosted instances.  Deleting all the values from your self hosted `exchange_rates` table or deleting / re-adding the problematic account _should_ fix this.

If we can get a reliable reproduction on this I'm happy to re-open and push a fix through.
